// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTZmtJ6IekVMSwW_e7hXtHu-tbwvDywiw',
    appId: '1:348250125784:web:a18c1931ccf7e7bf29eead',
    messagingSenderId: '348250125784',
    projectId: 'shopping-app-da2ee',
    authDomain: 'shopping-app-da2ee.firebaseapp.com',
    storageBucket: 'shopping-app-da2ee.firebasestorage.app',
    measurementId: 'G-SLJCEG2PGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWmXr7U9cWlz-S1dFXTqu20hQw72ul1dM',
    appId: '1:348250125784:android:02bcb73b44c8775c29eead',
    messagingSenderId: '348250125784',
    projectId: 'shopping-app-da2ee',
    storageBucket: 'shopping-app-da2ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8YrJK_P-YIJcIx50FoRfkVjOOGCd8MYA',
    appId: '1:348250125784:ios:6bb4f67e009f854d29eead',
    messagingSenderId: '348250125784',
    projectId: 'shopping-app-da2ee',
    storageBucket: 'shopping-app-da2ee.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8YrJK_P-YIJcIx50FoRfkVjOOGCd8MYA',
    appId: '1:348250125784:ios:6bb4f67e009f854d29eead',
    messagingSenderId: '348250125784',
    projectId: 'shopping-app-da2ee',
    storageBucket: 'shopping-app-da2ee.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTZmtJ6IekVMSwW_e7hXtHu-tbwvDywiw',
    appId: '1:348250125784:web:e65963a7420de66e29eead',
    messagingSenderId: '348250125784',
    projectId: 'shopping-app-da2ee',
    authDomain: 'shopping-app-da2ee.firebaseapp.com',
    storageBucket: 'shopping-app-da2ee.firebasestorage.app',
    measurementId: 'G-9BV4C114L2',
  );
}
